[tool.poetry]
name = "ta05-3"
version = "0.1.0"
description = ""
authors = ["Isaacmesa92 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
